

o_stem_animate_endings = {
        "nom-sg": "os",
        "voc-sg": "e",
        "acc-sg": "om",
        "gen-sg": "osio",
        "abl-sg": "od",
        "dat-sg": "oi",
        "loc-sg": "i",
        "ins-sg": "e",
        "nom-pl": "oi",
        "voc-pl": "oi",
        "acc-pl": "ons",
        "gen-pl": "om",
        "abl-pl": "omos",
        "dat-pl": "omos",
        "loc-pl": "oisu",
        "ins-pl": "ois",
        }
o_stem_neuter_endings = {
        "nom-sg": "om",
        "voc-sg": "om",
        "acc-sg": "om",
        "gen-sg": "osio",
        "abl-sg": "od",
        "dat-sg": "oi",
        "loc-sg": "i",
        "ins-sg": "e",
        "nom-pl": "a",
        "voc-pl": "a",
        "acc-pl": "a",
        "gen-pl": "om",
        "abl-pl": "omos",
        "dat-pl": "omos",
        "loc-pl": "oisu",
        "ins-pl": "ois",
        }
a_stem_endings = {
        "nom-sg": "a",
        "voc-sg": "u",
        "acc-sg": "am",
        "gen-sg": "as",
        "abl-sg": "ad",
        "dat-sg": "ai",
        "loc-sg": "i",
        "ins-sg": "e",
        "nom-pl": "ai",
        "voc-pl": "ai",
        "acc-pl": "ans",
        "gen-pl": "om",
        "abl-pl": "amos",
        "dat-pl": "amos",
        "loc-pl": "asu",
        "ins-pl": "abi",
        }
i_stem_endings = {
        "nom-sg": "is",
        "voc-sg": "i",
        "acc-sg": "im",
        "gen-sg": "ies",
        "abl-sg": "ied",
        "dat-sg": "iei",
        "loc-sg": "i",
        "ins-sg": "ie",
        "nom-pl": "ies",
        "voc-pl": "ies",
        "acc-pl": "ins",
        "gen-pl": "iom",
        "abl-pl": "imos",
        "dat-pl": "imos",
        "loc-pl": "isu",
        "ins-pl": "ibi",
        }
u_stem_endings = {
        "nom-sg": "us",
        "voc-sg": "u",
        "acc-sg": "um",
        "gen-sg": "ues",
        "abl-sg": "ued",
        "dat-sg": "uei",
        "loc-sg": "ui",
        "ins-sg": "ue",
        "nom-pl": "ues",
        "voc-pl": "ues",
        "acc-pl": "uns",
        "gen-pl": "uom",
        "abl-pl": "umos",
        "dat-pl": "umos",
        "loc-pl": "usu",
        "ins-pl": "ubi",
        }
